import { Schema, model } from 'mongoose';

const RegistrationSchema = new Schema({
  ProgrammeName: { type: String, required: true },
  Specialisation: { type: String },
  Session: { type: String },
  RegistrationId: { type: String, unique: true },
  Photo: { type: String }, // Store filename or path
  AadhaarCard: { type: String },
  AadhaarNumber: { type: String },
  AbcId: { type: String },
  AbcIdNumber: { type: String },
  DebId: { type: String },
  DebIdNumber: { type: String },
  StudentFirstName: { type: String, required: true },
  StudentMiddleName: { type: String },
  StudentLastName: { type: String, required: true },
  Gender: { type: String },
  DateOfBirth: { type: Date },
  Quota: { type: String },
  QuotaDocument: { type: String },
  Category: { type: String },
  CategoryCertificate: { type: String },
  SubCategory: { type: String },
  SubCategoryDocument: { type: String },
  Qualification: { type: String },
  StudentPhone: { type: String },
  WhatsappNo: { type: String },
  StudentEmail: { type: String },
  Grade: { type: String },
  Program: { type: String },
  CurrentHouseNo: { type: String },
  CurrentStreet: { type: String },
  CurrentArea: { type: String },
  CurrentLandmark: { type: String },
  CurrentCity: { type: String },
  CurrentDistrict: { type: String },
  CurrentState: { type: String },
  CurrentPincode: { type: String },
  CurrentCountry: { type: String },
  PermanentHouseNo: { type: String },
  PermanentStreet: { type: String },
  PermanentArea: { type: String },
  PermanentLandmark: { type: String },
  PermanentCity: { type: String },
  PermanentDistrict: { type: String },
  PermanentState: { type: String },
  PermanentPincode: { type: String },
  PermanentCountry: { type: String },
  SameAsCurrent: { type: Boolean, default: false },
  FatherFirstName: { type: String },
  FatherMiddleName: { type: String },
  FatherLastName: { type: String },
  FatherEmail: { type: String },
  FatherPhone: { type: String },
  FatherWhatsapp: { type: String },
  MotherFirstName: { type: String },
  MotherMiddleName: { type: String },
  MotherLastName: { type: String },
  MotherEmail: { type: String },
  MotherPhone: { type: String },
  MotherWhatsapp: { type: String },
  GuardianFirstName: { type: String },
  GuardianMiddleName: { type: String },
  GuardianLastName: { type: String },
  ParentEmail: { type: String },
  ParentPhone: { type: String },
  Relationship: { type: String },
  EmergencyName: { type: String },
  EmergencyPhone: { type: String },
  EmergencyRelationship: { type: String },
  PreviousSchool: { type: String },
  TenthBoard: { type: String },
  TenthSchool: { type: String },
  TenthSchoolAddress: { type: String },
  TenthYear: { type: Number },
  TenthPercentage: { type: Number },
  TenthMarksheet: { type: String },
  TwelfthBoard: { type: String },
  TwelfthSchool: { type: String },
  TwelfthSchoolAddress: { type: String },
  TwelfthStream: { type: String },
  TwelfthYear: { type: Number },
  TwelfthPercentage: { type: Number },
  TwelfthMarksheet: { type: String },
  UgDiplomaInstitute: { type: String },
  UgDiplomaCourse: { type: String },
  UgDiplomaSpecialization: { type: String },
  UgDiplomaYear: { type: Number },
  UgDiplomaPercentage: { type: Number },
  UgDiplomaMarksheet: { type: String },
  UgCollege: { type: String },
  UgCourse: { type: String },
  UgSpecialization: { type: String },
  UgYear: { type: Number },
  UgPercentage: { type: Number },
  UgMarksheet: { type: String },
  PgDiplomaInstitute: { type: String },
  PgDiplomaCourse: { type: String },
  PgDiplomaSpecialization: { type: String },
  PgDiplomaYear: { type: Number },
  PgDiplomaPercentage: { type: Number },
  PgDiplomaMarksheet: { type: String },
  PgUniversity: { type: String },
  PgCourse: { type: String },
  PgSpecialization: { type: String },
  PgYear: { type: Number },
  PgPercentage: { type: Number },
  PgMarksheet: { type: String },
  Gpa: { type: Number },
  Interests: { type: String },
  WhyApplying: { type: String },
  SpecialNeeds: { type: String },
  Medications: { type: String },
  AgreeTerms: { type: Boolean, default: false },
  Status: { type: String, enum: ['Pending', 'Approved', 'Rejected'], default: 'Pending' },
}, { timestamps: true });

export default model('Registration', RegistrationSchema);
